package report

const disclaimerText = "This report was generated by read-only analysis. No cloud resources were modified. " +
	"Potential savings figures are estimates based on observed data and stated assumptions; they are not guaranteed savings. " +
	"Verify all recommendations in a non-production environment before applying changes."
